CarStoreWeb/Models/CartViewModel.cs
using System;
using System.Collections.Generic;
using CarStoreShared;

namespace CarStoreWeb.Models
{
    public class CartViewModel
    {
        private Dictionary<CarItem, int> _cartItemsToDisplay = new Dictionary<CarItem, int>();

        public void AddCartItemToDisplay(CarItem carItem, int amount)
        {
            if(_cartItemsToDisplay == null)
            {
                _cartItemsToDisplay = new Dictionary<CarItem, int>();
            }

            _cartItemsToDisplay.Add(carItem, amount);
        }

        public Dictionary<CarItem, int> CartItemsToDisplay { get { return _cartItemsToDisplay; } }
    }
}

CarStoreWeb/Models/ErrorViewModel.cs
using System;

namespace CarStoreWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarStoreWeb/Models/StoreViewModel.cs
using System;
using System.Collections.Generic;
using CarStoreShared;

namespace CarStoreWeb.Models
{
    public class StoreViewModel
    {
        private List<CarItem> _carsToDisplay = new List<CarItem>();

        public void AddCarToDisplay(CarItem carItem)
        {
            if(_carsToDisplay == null)
            {
                _carsToDisplay = new List<CarItem>();
            }

            _carsToDisplay.Add(carItem);
        }

        public List<CarItem> CarsToDisplay { get { return _carsToDisplay; } }
    }
}

CarStoreWeb/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarStoreWeb.Data;
using CarStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CarStoreWeb.Controllers
{
    public class CartController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["CartItems"] = CartProxy.GetInstance().GetCurrentNumberOfItems(HttpContext.Session.Id);

            var cartModel = new CartViewModel();
            var cartItems = CartProxy.GetInstance().GetCurrentCartItems(HttpContext.Session.Id);

            Dictionary<string, int> preDict = new Dictionary<string, int>();
            foreach (var item in cartItems)
            {
                if(string.IsNullOrWhiteSpace(item))
                {
                    continue;
                }

                if(preDict.ContainsKey(item))
                {
                    preDict[item]++;
                }
                else
                {
                    preDict.Add(item, 1);
                }               
            }

            double total = 0.0;
            foreach(var key in preDict.Keys)
            {
                var car = InventoryProxy.GetInstance().GetInventoryItem(key);
                cartModel.AddCartItemToDisplay(car, preDict[key]);

                total = total + (car.CarPrice * preDict[key]);

            }

            ViewData["Total"] = string.Format("{0:N2}", total);


            return View(cartModel);
        }

        public IActionResult Remove(string carManufacturerAndId)
        {
            CartProxy.GetInstance().RemoveItem(HttpContext.Session.Id, carManufacturerAndId);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Order(string email)
        {
            var cartModel = new CartViewModel();
            ViewData["CustomerEmail"] = email;
            ViewData["OrderResult"] = "Your order has been placed. An email confirmation will follow shortly.";
            ViewData["OrderBool"] = true;

            ViewData["CartItems"] = CartProxy.GetInstance().GetCurrentNumberOfItems(HttpContext.Session.Id);

            if(string.IsNullOrWhiteSpace(email))
            {
                ViewData["OrderResult"] = "Email address entered is not valid. Please try again.";
                ViewData["OrderBool"] = false;
            } else
            {
                if(!email.Contains("@") || !email.Contains("."))
                {
                    ViewData["OrderResult"] = "Email address entered is not valid. Please try again.";
                    ViewData["OrderBool"] = false;
                }
            }

            var cartItems = CartProxy.GetInstance().GetCurrentCartItems(HttpContext.Session.Id);

            Dictionary<string, int> preDict = new Dictionary<string, int>();
            foreach(var item in cartItems)
            {
                if(string.IsNullOrWhiteSpace(item))
                {
                    continue;
                }

                if(preDict.ContainsKey(item))
                {
                    preDict[item]++;
                } else
                {
                    preDict.Add(item, 1);
                }
            }

            double total = 0.0;
            foreach (var key in preDict.Keys)
            {
                var car = InventoryProxy.GetInstance().GetInventoryItem(key);
                cartModel.AddCartItemToDisplay(car, preDict[key]);
                total = total + (car.CarPrice * preDict[key]);
            }

            ViewData["Total"] = string.Format("{0:N2}", total);

            if((bool)ViewData["OrderBool"] == false)
            {
                return View(cartModel);
            }

            var orderResult = PurchaseProxy.GetInstance().TryOrder(HttpContext.Session.Id, email);

            var orderArray = orderResult.Split(";");
            if(orderArray[0].Equals("Success"))
            {
                ViewData["OrderBool"] = true;
                ViewData["OrderResult"] = orderArray[1];
                ViewData["CartItems"] = "0";
            }
            else
            {
                ViewData["OrderBool"] = false;
                ViewData["OrderResult"] = orderArray[1];
            }

            return View(cartModel);
        }
    }
}

CarStoreWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CarStoreWeb.Models;
using Microsoft.AspNetCore.Http;
using CarStoreWeb.Data;

namespace CarStoreWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("SessionBirthTime", DateTime.Now.ToFileTime().ToString());
            HttpContext.Session.GetString("SessionBirthTime");
            ViewData["CartItems"] = CartProxy.GetInstance().GetCurrentNumberOfItems(HttpContext.Session.Id);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarStoreWeb/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarStoreWeb.Data;
using CarStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CarStoreWeb.Controllers
{
    public class StoreController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["CartItems"] = CartProxy.GetInstance().GetCurrentNumberOfItems(HttpContext.Session.Id);
            var inventory = InventoryProxy.GetInstance().GetInventory();

            var storeModel = new StoreViewModel();

            foreach(var key in inventory.Keys)
            {
                storeModel.AddCarToDisplay(inventory[key]);
            }

            return View(storeModel);
        }

        public string AddToCart(string manufacturerAndIdString)
        {
            if(string.IsNullOrWhiteSpace(manufacturerAndIdString))
            {
                throw new InvalidOperationException();
            }

            if(!manufacturerAndIdString.Contains(":"))
            {
                throw new InvalidOperationException();
            }

            var manufacturerAndIdArray = manufacturerAndIdString.Split(":");
            if(manufacturerAndIdArray.Length != 2)
            {
                throw new InvalidOperationException();
            }

            return CartProxy.GetInstance().AddItem(HttpContext.Session.Id, manufacturerAndIdString).ToString();
        }
    }
}

CarStoreWeb/Views/Cart/Index.cshtml
@using CarStoreShared
@model CarStoreWeb.Models.CartViewModel
@{
    ViewData["Title"] = "Your cart with " + ViewData["CartItems"] + " items";
}
<h2>@ViewData["Title"]</h2>

@if (Model.CartItemsToDisplay.Keys.Count > 0)
{
    <table>
        @foreach (CarItem car in Model.CartItemsToDisplay.Keys)
        {
            <tr>
                <td width="100">@Model.CartItemsToDisplay[car] x</td>
                <td><img src="@car.CarPicture" alt="@car.CarManufacturer:@car.CarId" width="75" /></td>
                <td width="300"><p> @string.Format("{0} {1}", car.CarManufacturer, car.CarId) </p></td>
                <td><p style="font-size: 8pt;"> @Html.DisplayFor(item => car.CarInfo) </p></td>
                <td width="150">
                    <p><i>&#163; @String.Format("{0:N2}", car.CarPrice) </i>per item</p>
                    <p><b>&#163; @String.Format("{0:N2}", (Model.CartItemsToDisplay[car] * car.CarPrice)) </b> in total</p>
                    <p>@Html.ActionLink("Remove from cart", "Remove", "Cart", new { carManufacturerAndId = (car.CarManufacturer + ":" + car.CarId) })</p>

                </td>
            </tr>
        }
    </table>
    <h3>Current Total: &#163; @ViewData["Total"]</h3>
    @using (Html.BeginForm("Order", "Cart"))
    {
        <p>Enter your e-mail address to send us your order: <input type="text" name="EMail" /></p>
        <p><input type="submit" value="Order now" /></p>
        <p>Our automated system will confirm your order immediately.</p>
    }
}
else
{
    <p>The Cart is currently empty. Please head to the <b>Store</b> to add items to the cart.</p>
}

CarStoreWeb/Views/Cart/Order.cshtml
@using CarStoreShared
@model CarStoreWeb.Models.CartViewModel

@{
    ViewData["Title"] = "Order for " + ViewData["CustomerEMail"];
}
<h2>@ViewData["Title"]</h2>

@if ((bool)ViewData["OrderBool"] == true)
{
    <div style="margin: 5px; padding: 10px; background-color: #99ff99; padding-top:10px; padding-bottom:2px">
        <p>@ViewData["OrderResult"]</p>
    </div>
}
else
{
    <div style="margin: 5px; padding: 10px; background-color: #ff9999; padding-top:10px; padding-bottom:2px;">
        <p>@ViewData["OrderResult"]</p>
    </div>
}

@if (Model.CartItemsToDisplay.Keys.Count > 0)
{
    <table>
        @foreach (CarItem car in Model.CartItemsToDisplay.Keys)
        {
            <tr>
                <td width="100">@Model.CartItemsToDisplay[car] x</td>
                <td><img src="@car.CarPicture" alt="@car.CarManufacturer:@car.CarId" width="75" /></td>
                <td width="300"><p> @string.Format("{0} {1}", car.CarManufacturer, car.CarId) </p></td>
                <td><p style="font-size: 8pt;"> @Html.DisplayFor(item => car.CarInfo) </p></td>
                <td width="150">
                    <p><i>&#163; @String.Format("{0:N2}", car.CarPrice) </i>per item</p>
                    <p><b>&#163; @String.Format("{0:N2}", (Model.CartItemsToDisplay[car] * car.CarPrice)) </b> in total</p>

                </td>
            </tr>
        }
    </table>
    <h3>Order Total: &#163; @ViewData["Total"]</h3>
}

CarStoreWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="~/images/banner1.png" alt="Tesla CyberTruck" class="d-block w-100" />
        <div class="carousel-caption d-none d-md-block">
            <h5>CyberTruck</h5>
            <p>
                Discover the exciting new CyberTruck! Order today!
            </p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="~/images/banner2.jpg" alt="Ferrari Roma" class="d-block w-100" />
        <div class="carousel-caption d-none d-md-block">
            <h5>Roma</h5>
            <p>
                Find your perfect match 
            </p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="~/images/banner3.jpg" alt="BMW M8" class="d-block w-100" />
        <div class="carousel-caption d-none d-md-block">
            <h5>BMW M8 Gran Coupe</h5>
            <p>
                More cars available than any other retailer
            </p>
        </div>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-md-5">
		<h2>Welcome to Cars Unlimited</h2>
            <p>Please use the <b>"Shop"</b> option to start browsing.</p>
            <p>Once you are ready to place your order, click <b>"Cart"</b>, and send us your order</p>
            <p>We will confirm your order over e-mail as soon as we receive it.</p>
    </div>
    <div class="col-md-5">
		<h3>More about this website...</h3>
        <p>This is a demo site created to showcase Docker container and deploying to Azure resources from Azure DevOps.</p>
		<p>E-Mail services are provided by non-code services.</p>
    </div>
</div>

CarStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cars Unlimited</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cars Unlimited</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Store" asp-action="Index">Store</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">Cart (<span id='cartItems'>@ViewData["CartItems"]</span>)</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Cars Unlimited
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CarStoreWeb/Views/Store/Index.cshtml
@using CarStoreShared
@model CarStoreWeb.Models.StoreViewModel

@{
    ViewData["Title"] = "Store";
}
<h2>@ViewData["Title"]</h2>

@if (Model.CarsToDisplay.Count > 0)
{
    <table>
        @foreach (CarItem car in Model.CarsToDisplay)
        {
            <tr>
                <td><img src="@car.CarPicture" alt="@car.CarManufacturer:@car.CarId" width="200" /></td>
                <td width="200"><p> @string.Format("{0} {1}", car.CarManufacturer, car.CarId)</td>
                <td><p> @Html.DisplayFor(item => car.CarInfo) </p></td>
                <td width="150">
                    <p>&#163; @String.Format("{0:N2}", car.CarPrice)</p>
                    @if (car.CarsInStock > 0)
                    {
                        <p><b>In Stock</b></p>
                        <p><a href="javascript:AddToCart('@car.CarManufacturer:@car.CarId')">Add to Cart</a></p>
                    }
                    else
                    {
                        <p><i>Out of stock</i></p>
                    }


                </td>
            </tr>
        }
    </table>
}
else
{
    <p>It looks like there are no cars in our online inventory. Please give us a call, and we'll be more than happy to help you.</p>
}

<script language="javascript" type="text/javascript">

    function AddToCart(manufacturerAndIdString) {
        $.ajax({
            url: ("/Store/AddToCart?manufacturerAndIdString=" + manufacturerAndIdString + "&randomNumber=" + Math.floor((Math.random() * 10000) + 1))
        })
            .done(function (data) {
                document.getElementById('cartItems').innerHTML = data;
            });
    }
</script>